# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-06-07 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20180605_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='source',
            field=models.SmallIntegerField(choices=[(0, '转介绍'), (1, 'QQ群'), (2, '官网'), (3, '百度推广'), (4, '51CTO'), (5, '知乎'), (6, '其他')], verbose_name='来源'),
        ),
        migrations.RemoveField(
            model_name='role',
            name='menu',
        ),
        migrations.AddField(
            model_name='role',
            name='menu',
            field=models.ManyToManyField(blank=True, to='crm.Menu'),
        ),
    ]
