# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-06-12 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=16, null=True, verbose_name='姓名')),
                ('mobile', models.PositiveIntegerField(verbose_name='手机号')),
            ],
        ),
    ]
